image: node:latest
before_script:
  - yarn install
cache:
  paths:
    - node_modules/
test:
  stage: test
  script:
    - yarn test
pages:
  stage: deploy
  script:
    - yarn build
    - rm -rf public && mkdir public
    - mv build/* public
  artifacts:
    paths:
      - public
  only:
    - master
