import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import type { Plugin } from "vite";

const MODULE_ID = "virtual:changelog";
const RESOLVED_ID = `\0${MODULE_ID}`;
const GIT_CLIFF = fileURLToPath(new URL("../node_modules/.bin/git-cliff", import.meta.url));

/**
 * Provides `virtual:changelog`: the changelog markdown generated by git-cliff from the git
 * history at build time, so the in-app changelog always matches the commits being built
 * (commits after the latest tag show as "Unreleased"). Needs the full history and tags, so CI
 * checks out with `fetch-depth: 0`. The dev server generates it once at start-up.
 */
export const changelogPlugin = (): Plugin => ({
  name: "poo-game:changelog",
  resolveId: (source) => (source === MODULE_ID ? RESOLVED_ID : undefined),
  load(id) {
    if (id !== RESOLVED_ID) return undefined;
    const markdown = execFileSync(GIT_CLIFF, [], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    return `export default ${JSON.stringify(markdown)};`;
  },
});
